version: 2.1

orbs:
    node: circleci/node@1.1.6

executors:
    node:
        docker:
            - image: circleci/node:10.20

# Docs: https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

jobs:
    build-push-docker-image:
        machine: true
        working_directory: /home/circleci/repo
        steps:
            - checkout
            - run:
                  name: docker_build
                  command: |
                      echo TAG computed: $CIRCLE_SHA1-$CIRCLE_BUILD_NUM
                      echo TAG computed with workflow: $CIRCLE_SHA1-$CIRCLE_WORKFLOW_ID
                      # IMAGE_TAG=`echo $CIRCLE_SHA1-$CIRCLE_BUILD_NUM`
                      # docker tag sh-farmforecast-be-admin:latest ${ECR_REPOSITORY}/${ECR_REPO_NAME}:${IMAGE_TAG}
                      # docker push ${ECR_REPOSITORY}/${ECR_REPO_NAME}:${IMAGE_TAG}

    deploy-admin:
        machine: true
        working_directory: /home/circleci/repo
        parameters:
            env:
                type: enum
                enum: ["stage", "production"]
                default: "stage"
        steps:
            - checkout:
                  path: /home/circleci/repo
            - run:
                  name: Kube Deployment sh-farmforecast-be-admin
                  command: |
                      echo TAG computed: $CIRCLE_SHA1-$CIRCLE_BUILD_NUM
                      echo TAG computed with prev: $CIRCLE_SHA1-$CIRCLE_PREVIOUS_BUILD_NUM
                      echo TAG computed with workflow: $CIRCLE_SHA1-$CIRCLE_WORKFLOW_ID
                      # IMAGE_TAG=`echo $CIRCLE_SHA1-$CIRCLE_BUILD_NUM`
                      # docker run --add-host .... --env IMAGE_TAG=${IMAGE_TAG} ... --deploy=true

    send-notifications:
        machine: true
        steps:
            - run:
                  name: Send push notification
                  command: echo "Sending notifications... DONE"

workflows:
    version: 2

    farmforecast-admin:
        jobs:
            - build-push-docker-image
            - deploy-admin:
                  name: deploy-admin-stage
                  env: stage
                  requires:
                      - build-push-docker-image

    notifications:
        triggers:
            - schedule:
                  cron: "0 4 * * *"
                  filters:
                      branches:
                          only: master
        jobs:
            - send-notifications
